name: Check For Chrome Updates

on:
  schedule:
    # Run at 10am daily
    - cron: '0 10 * * *'

concurrency:
  group: ${{ github.ref }}

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn Install
        run: yarn
        env:
          SA_REPLAY_SKIP_BINARY_DOWNLOAD: true
          SA_SKIP_DOWNLOAD: false
          HERO_SKIP_CHROME_DOWNLOAD: false

      - name: Check for Chrome Updates
        run: node ./scripts/checkChromeForUpdates.js

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Automatic Stable Channel check
