name: Sync Version Releases

on:
  - push
  - workflow_dispatch

concurrency:
  group: ${{ github.ref }}

jobs:

  windows:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn Install
        run: yarn

      - name: Synchronize Versions File
        run: node ./scripts/syncVersions.js
        env:
          SYNC_OS_KEYS: win32,win64
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SA_SHOW_REPLAY: false
  ubuntu:
    runs-on: ubuntu-latest
    needs: windows

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn Install
        run: yarn

      - name: Synchronize Versions File
        run: node ./scripts/syncVersions.js
        env:
          SYNC_OS_KEYS: linux
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: main
          commit_message: Sync Versions Cleanup

  mac:
    runs-on: macos-latest
    needs: ubuntu

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Yarn Install
        run: yarn

      - name: Import Certs
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p $MACOS_CERTIFICATE_PWD build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p $MACOS_CERTIFICATE_PWD build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k $MACOS_CERTIFICATE_PWD build.keychain

      - name: Synchronize Versions File
        run: node ./scripts/syncVersions.js
        env:
          SYNC_OS_KEYS: mac,mac_arm64
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
